In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('data/원본/상주(야간)·주간인구_20230713151847.xlsx')

C:\Users\Playdata\AppData\Local\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [3]:
df

,자치구별(1),자치구별(2),2020,2020.1,2020.2,2020.3,2020.4,2020.5,2020.6,2020.7,2020.8
0,자치구별(1),자치구별(2),상주인구 (명),유입인구 (명),유입인구 (명),유입인구 (명),유출인구 (명),유출인구 (명),유출인구 (명),주간인구 (명),주간인구지수 (%)
1,자치구별(1),자치구별(2),소계,소계,통근,통학,소계,통근,통학,소계,소계
2,서울시,소계,9230846,1436347,1305735,130612,622380,566411,55969,10044813,109
3,NaN,종로구,141316,236168,215753,20415,31687,27898,3789,345797,245
4,NaN,중구,118450,289569,273093,16476,27795,24388,3407,380224,321
5,NaN,용산구,212043,113823,103603,10220,60758,55127,5631,265108,125
6,NaN,성동구,282193,121304,105715,15589,85702,77763,7939,317795,113
7,NaN,광진구,334190,78921,60920,18001,112066,102899,9167,301045,90
8,NaN,동대문구,331973,105085,85341,19744,87836,78326,9510,349222,105
9,NaN,중랑구,377150,43417,38814,4603,110919,101838,9081,309648,82
10,NaN,성북구,425639,92714,55350,37364,119879,108350,11529,398474,94
11,NaN,강북구,293755,36465,32774,3691,86573,77911,8662,243647,83
12,NaN,도봉구,311839,34613,30287,4326,94550,84905,9645,251902,81
13,NaN,노원구,504411,76609,53906,22703,146125,133473,12652,434895,86
14,NaN,은평구,456474,39435,36556,2879,142846,132063,10783,353063,77
15,NaN,서대문구,304192,103785,67662,36123,87563,79456,8107,320414,105
16,NaN,마포구,354420,182226,165207,17019,108630,97848,10782,428016,121
17,NaN,양천구,431427,54767,52477,2290,132112,118781,13331,354082,82
18,NaN,강서구,555402,130856,125420,5436,147505,135761,11744,538753,97
19,NaN,구로구,392040,134257,127417,6840,120595,111860,8735,405702,104
20,NaN,금천구,224123,123049,121599,1450,58969,54593,4376,288203,129
21,NaN,영등포구,360059,253420,249206,4214,99263,90172,9091,514216,143
22,NaN,동작구,377366,77725,55279,22446,120652,110134,10518,334439,89
23,NaN,관악구,479969,62067,48169,13898,157792,146611,11181,384244,80
24,NaN,서초구,394955,269918,257915,12003,111171,98430,12741,553702,140
25,NaN,강남구,499028,575719,561357,14362,113147,99969,13178,961600,193
26,NaN,송파구,631722,180409,176194,4215,177642,159981,17661,634489,100
27,NaN,강동구,436710,66435,63873,2562,127012,116026,10986,376133,86

In [4]:
df1 = df.loc[3:,['자치구별(2)','2020','2020.7','2020.1']]
df1.rename(columns = {'자치구별(2)':'시군구','2020':'상주인구','2020.7':'주간인구','2020.1':'유입인구'}, inplace = True)

In [5]:
df1.reset_index(drop = True)

     시군구    상주인구    주간인구    유입인구
0    종로구  141316  345797  236168
1     중구  118450  380224  289569
2    용산구  212043  265108  113823
3    성동구  282193  317795  121304
4    광진구  334190  301045   78921
5   동대문구  331973  349222  105085
6    중랑구  377150  309648   43417
7    성북구  425639  398474   92714
8    강북구  293755  243647   36465
9    도봉구  311839  251902   34613
10   노원구  504411  434895   76609
11   은평구  456474  353063   39435
12  서대문구  304192  320414  103785
13   마포구  354420  428016  182226
14   양천구  431427  354082   54767
15   강서구  555402  538753  130856
16   구로구  392040  405702  134257
17   금천구  224123  288203  123049
18  영등포구  360059  514216  253420
19   동작구  377366  334439   77725
20   관악구  479969  384244   62067
21   서초구  394955  553702  269918
22   강남구  499028  961600  575719
23   송파구  631722  634489  180409
24   강동구  436710  376133   66435

In [6]:
crime = pd.read_excel('data/git_copy/data_21_전처리/범죄/범죄발생_검거_발생율_검거율_2021.xlsx', index_col = 0)

In [7]:
crime = crime.loc[:, ['시군구', '범죄발생률']]

In [8]:
df2 = pd.merge(df1, crime, how = 'inner', on = '시군구')

In [9]:
df3 = df2.loc[:,['시군구','유입인구','범죄발생률']]
df3['유입인구'] = df3['유입인구'].astype(int)

In [10]:
df3.corr()

C:\Users\Playdata\AppData\Local\Temp\ipykernel_17268\3136175663.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df3.corr()

           유입인구     범죄발생률
유입인구   1.000000  0.544468
범죄발생률  0.544468  1.000000

In [11]:
# df3.to_excel('data/preprocessing/유입인구_범죄발생율.xlsx')

In [12]:
df4 = df1.sort_values('유입인구',  ascending=  False)

In [13]:
df4['주간인구 대비 유입인구'] = df4['주간인구']/df4['유입인구']
df4.reset_index(inplace = True, drop = True)
# df4 = df4.iloc[:,1:]

In [14]:
df4

     시군구    상주인구    주간인구    유입인구 주간인구 대비 유입인구
0    강남구  499028  961600  575719     1.670259
1     중구  118450  380224  289569     1.313069
2    서초구  394955  553702  269918     2.051371
3   영등포구  360059  514216  253420     2.029106
4    종로구  141316  345797  236168     1.464199
5    마포구  354420  428016  182226      2.34882
6    송파구  631722  634489  180409     3.516948
7    구로구  392040  405702  134257     3.021831
8    강서구  555402  538753  130856     4.117144
9    금천구  224123  288203  123049     2.342181
10   성동구  282193  317795  121304     2.619823
11   용산구  212043  265108  113823     2.329125
12  동대문구  331973  349222  105085     3.323234
13  서대문구  304192  320414  103785     3.087286
14   성북구  425639  398474   92714     4.297884
15   광진구  334190  301045   78921     3.814511
16   동작구  377366  334439   77725      4.30285
17   노원구  504411  434895   76609     5.676813
18   강동구  436710  376133   66435     5.661669
19   관악구  479969  384244   62067     6.190794
20   양천구  431427  354082   54767     6.465244
21   중랑구  377150  309648   43417     7.131953
22   은평구  456474  353063   39435     8.953037
23   강북구  293755  243647   36465     6.681667
24   도봉구  311839  251902   34613      7.27767

In [15]:
df5 = pd.merge(df4, crime, how = 'inner', on = '시군구')

In [16]:
df5

     시군구    상주인구    주간인구    유입인구 주간인구 대비 유입인구     범죄발생률
0    강남구  499028  961600  575719     1.670259  1.142804
1     중구  118450  380224  289569     1.313069  2.170927
2    서초구  394955  553702  269918     2.051371  0.878493
3   영등포구  360059  514216  253420     2.029106  1.042384
4    종로구  141316  345797  236168     1.464199  1.763455
5    마포구  354420  428016  182226      2.34882  0.934811
6    송파구  631722  634489  180409     3.516948  0.709977
7    구로구  392040  405702  134257     3.021831  0.827708
8    강서구  555402  538753  130856     4.117144  0.671993
9    금천구  224123  288203  123049     2.342181  0.995953
10   성동구  282193  317795  121304     2.619823  0.721627
11   용산구  212043  265108  113823     2.329125  1.003435
12  동대문구  331973  349222  105085     3.323234  0.840611
13  서대문구  304192  320414  103785     3.087286  0.721665
14   성북구  425639  398474   92714     4.297884  0.547778
15   광진구  334190  301045   78921     3.814511  0.875429
16   동작구  377366  334439   77725      4.30285  0.667150
17   노원구  504411  434895   76609     5.676813  0.665118
18   강동구  436710  376133   66435     5.661669  0.741309
19   관악구  479969  384244   62067     6.190794  0.889781
20   양천구  431427  354082   54767     6.465244  0.669276
21   중랑구  377150  309648   43417     7.131953  0.819118
22   은평구  456474  353063   39435     8.953037  0.679837
23   강북구  293755  243647   36465     6.681667  0.760503
24   도봉구  311839  251902   34613      7.27767  0.582391

In [17]:
# df4 # 주간인구와 상주인구의 차이가 클 수록 값이 낮게나올 것이다

In [18]:
df6 = df5.sort_values('주간인구 대비 유입인구', ascending = True)

In [19]:
df6.reset_index(drop = True, inplace = True)

In [20]:
df6

     시군구    상주인구    주간인구    유입인구 주간인구 대비 유입인구     범죄발생률
0     중구  118450  380224  289569     1.313069  2.170927
1    종로구  141316  345797  236168     1.464199  1.763455
2    강남구  499028  961600  575719     1.670259  1.142804
3   영등포구  360059  514216  253420     2.029106  1.042384
4    서초구  394955  553702  269918     2.051371  0.878493
5    용산구  212043  265108  113823     2.329125  1.003435
6    금천구  224123  288203  123049     2.342181  0.995953
7    마포구  354420  428016  182226      2.34882  0.934811
8    성동구  282193  317795  121304     2.619823  0.721627
9    구로구  392040  405702  134257     3.021831  0.827708
10  서대문구  304192  320414  103785     3.087286  0.721665
11  동대문구  331973  349222  105085     3.323234  0.840611
12   송파구  631722  634489  180409     3.516948  0.709977
13   광진구  334190  301045   78921     3.814511  0.875429
14   강서구  555402  538753  130856     4.117144  0.671993
15   성북구  425639  398474   92714     4.297884  0.547778
16   동작구  377366  334439   77725      4.30285  0.667150
17   강동구  436710  376133   66435     5.661669  0.741309
18   노원구  504411  434895   76609     5.676813  0.665118
19   관악구  479969  384244   62067     6.190794  0.889781
20   양천구  431427  354082   54767     6.465244  0.669276
21   강북구  293755  243647   36465     6.681667  0.760503
22   중랑구  377150  309648   43417     7.131953  0.819118
23   도봉구  311839  251902   34613      7.27767  0.582391
24   은평구  456474  353063   39435     8.953037  0.679837

In [21]:
judge = pd.read_excel('data/preprocessing/최종판별.xlsx', index_col = 0)

In [22]:
df7 = pd.merge(df6,judge, how = 'inner', on = '시군구')

In [23]:
df7.to_csv('data/preprocessing/찐막/유입인구_투입지수.csv')

new

In [24]:
n = pd.read_excel('data/원본/서울시_구별_경찰투입률.xlsx', index_col = 0)

In [25]:
n = n.iloc[:, 1:]

In [26]:
n = n.loc[:, ['시군구', '경찰투입지수']]
n.head()

   시군구    경찰투입지수
0   중구  2.185335
1  금천구  2.729320
2  종로구  2.980134
3  용산구  3.329487
4  광진구  3.954329

In [27]:
df7.drop(columns = '경찰투입지수', inplace = True)

In [28]:
df8 = pd.merge(df7, n, how = 'inner', on = '시군구')

In [29]:
# df8.to_csv('data/preprocessing/ㅅ발.csv')

In [30]:
df8

,시군구,상주인구,주간인구,유입인구,주간인구 대비 유입인구,범죄발생률,경찰1인당 담당인구수,판별,경찰투입지수
0,중구,118450,380224,289569,1.313069,2.170927,98.421957,False,2.185335
1,종로구,141316,345797,236168,1.464199,1.763455,101.176974,False,2.980134
2,강남구,499028,961600,575719,1.670259,1.142804,277.216495,False,6.379531
3,영등포구,360059,514216,253420,2.029106,1.042384,314.684458,False,4.497810
4,서초구,394955,553702,269918,2.051371,0.878493,285.632807,False,5.929316
5,용산구,212043,265108,113823,2.329125,1.003435,254.871106,False,3.329487
6,금천구,224123,288203,123049,2.342181,0.995953,307.265997,False,2.729320
7,마포구,354420,428016,182226,2.34882,0.934811,324.495287,False,4.483530
8,성동구,282193,317795,121304,2.619823,0.721627,323.037528,False,4.127460
9,구로구,392040,405702,134257,3.021831,0.827708,396.575330,True,4.272136
10,서대문구,304192,320414,103785,3.087286,0.721665,363.243959,True,4.455620
11,동대문구,331973,349222,105085,3.323234,0.840611,295.554996,False,4.626666
12,송파구,631722,634489,180409,3.516948,0.709977,468.240480,True,6.852355
13,광진구,334190,301045,78921,3.814511,0.875429,368.471264,True,3.954329
14,강서구,555402,538753,130856,4.117144,0.671993,500.663212,True,6.541299
15,성북구,425639,398474,92714,4.297884,0.547778,325.067947,False,7.888894
16,동작구,377366,334439,77725,4.30285,0.667150,405.307297,True,4.680403
17,강동구,436710,376133,66435,5.661669,0.741309,443.836346,True,4.813925
18,노원구,504411,434895,76609,5.676813,0.665118,471.130833,True,5.658791
19,관악구,479969,384244,62067,6.190794,0.889781,405.726239,True,4.767881
20,양천구,431427,354082,54767,6.465244,0.669276,442.087341,True,5.234845
21,강북구,293755,243647,36465,6.681667,0.760503,326.389428,False,4.148647
22,중랑구,377150,309648,43417,7.131953,0.819118,363.867224,True,4.402029
23,도봉구,311839,251902,34613,7.27767,0.582391,439.907713,True,4.523826
24,은평구,456474,353063,39435,8.953037,0.679837,372.791406,True,6.329123

In [31]:
df9 = df.loc[3:,['자치구별(2)','2020.4']]

In [33]:
df9

   자치구별(2)  2020.4
3      종로구   31687
4       중구   27795
5      용산구   60758
6      성동구   85702
7      광진구  112066
8     동대문구   87836
9      중랑구  110919
10     성북구  119879
11     강북구   86573
12     도봉구   94550
13     노원구  146125
14     은평구  142846
15    서대문구   87563
16     마포구  108630
17     양천구  132112
18     강서구  147505
19     구로구  120595
20     금천구   58969
21    영등포구   99263
22     동작구  120652
23     관악구  157792
24     서초구  111171
25     강남구  113147
26     송파구  177642
27     강동구  127012

In [34]:
df9.rename(columns = {'자치구별(2)':'시군구','2020.4':'유출인구'}, inplace = True)
df10 = pd.merge(df8, df9, how = 'inner', on = '시군구')

In [35]:
df11 = df10.iloc[:, [0,1,2,-1,3,4,5,6,8,7]]

In [37]:
df11.to_excel('data/서울특별시_경찰지수_유입인구.xlsx')